name: kost_akbar
description: "Aplikasi mobile penghuni Kost Akbar — Sistem Informasi Pengelolaan Kost (Sprint 1)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Koneksi ke REST API Laravel
  http: ^1.2.2

  # State management sederhana (auth & data katalog)
  provider: ^6.1.2

  # Penyimpanan token login di device
  shared_preferences: ^2.3.2

  # Format angka Rupiah & tanggal Indonesia
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
